const Data = [
  {
    id: 1,
    day: 'Sunday',
    date: '01/30/2021',
    startTime: 'N/A',
    endTime: 'N/A',
    totleHours: 8,
    floatingDay: false,
    holiday: true,
    vacation: false,
  },
  {
    id: 2,
    day: 'Monday',
    date: '01/31/2021',
    startTime: '8',
    endTime: '14',
    totleHours: 8,
    floatingDay: false,
    holiday: false,
    vacation: false,
  },
  {
    id: 3,
    day: 'Tuesday',
    date: '02/01/2022',
    startTime: '8',
    endTime: '14',
    totleHours: 8,
    floatingDay: false,
    holiday: false,
    vacation: false,
  },
  {
    id: 4,
    day: 'Wednesday',
    date: '02/02/2022',
    startTime: '8',
    endTime: '14',
    totleHours: 8,
    floatingDay: false,
    holiday: false,
    vacation: false,
  },
  {
    id: 5,
    day: 'Thursday',
    date: '02/03/2022',
    startTime: '8',
    endTime: '14',
    totleHours: 8,
    floatingDay: false,
    holiday: false,
    vacation: false,
  },
  {
    id: 6,
    day: 'Friday',
    date: '02/04/2022',
    startTime: '8',
    endTime: '14',
    totleHours: 8,
    floatingDay: false,
    holiday: false,
    vacation: false,
  },
  {
    id: 7,
    day: 'Satday',
    date: '02/05/2022',
    startTime: 'N/A',
    endTime: 'N/A',
    totleHours: 8,
    floatingDay: false,
    holiday: true,
    vacation: false,
  },
  {
    id: 8,
    day: 'Sunday',
    date: '02/06/2022',
    startTime: 'N/A',
    endTime: 'N/A',
    totleHours: 8,
    floatingDay: false,
    holiday: true,
    vacation: false,
  },
  {
    id: 9,
    day: 'Monday',
    date: '02/07/2022',
    startTime: '9',
    endTime: '16',
    totleHours: 8,
    floatingDay: false,
    holiday: false,
    vacation: false,
  },
  {
    id: 10,
    day: 'Tuesday',
    date: '02/08/2022',
    startTime: '9',
    endTime: '16',
    totleHours: 8,
    floatingDay: false,
    holiday: false,
    vacation: false,
  },
  {
    id: 11,
    day: 'Wednesday',
    date: '02/09/2022',
    startTime: '10',
    endTime: '14',
    totleHours: 8,
    floatingDay: false,
    holiday: false,
    vacation: false,
  },
  {
    id: 12,
    day: 'Thursday',
    date: '02/10/2022',
    startTime: '9',
    endTime: '14',
    totleHours: 8,
    floatingDay: false,
    holiday: false,
    vacation: false,
  },
  {
    id: 13,
    day: 'Friday',
    date: '02/11/2022',
    startTime: '8',
    endTime: '18',
    totleHours: 8,
    floatingDay: false,
    holiday: false,
    vacation: false,
  },
  {
    id: 14,
    day: 'Satday',
    date: '02/12/2022',
    startTime: 'N/A',
    endTime: 'N/A',
    totleHours: 8,
    floatingDay: false,
    holiday: true,
    vacation: false,
  },
  {
    id: 15,
    day: 'Sunday',
    date: '02/13/2022',
    startTime: 'N/A',
    endTime: 'N/A',
    totleHours: 8,
    floatingDay: false,
    holiday: true,
    vacation: false,
  },
  {
    id: 16,
    day: 'Monday',
    date: '02/14/2022',
    startTime: '9',
    endTime: '15',
    totleHours: 8,
    floatingDay: false,
    holiday: false,
    vacation: false,
  },
  {
    id: 17,
    day: 'Tuesday',
    date: '02/15/2022',
    startTime: '9',
    endTime: '17',
    totleHours: 8,
    floatingDay: false,
    holiday: false,
    vacation: false,
  },
  {
    id: 18,
    day: 'Wednesday',
    date: '02/16/2022',
    startTime: '9',
    endTime: '17',
    totleHours: 8,
    floatingDay: false,
    holiday: false,
    vacation: false,
  },
  {
    id: 19,
    day: 'Thursday',
    date: '02/17/2022',
    startTime: '9',
    endTime: '17',
    totleHours: 8,
    floatingDay: false,
    holiday: false,
    vacation: false,
  },
  {
    id: 20,
    day: 'Friday',
    date: '02/18/2022',
    startTime: '9',
    endTime: '17',
    totleHours: 8,
    floatingDay: false,
    holiday: false,
    vacation: false,
  },
  {
    id: 21,
    day: 'Satday',
    date: '02/19/2022',
    startTime: 'N/A',
    endTime: 'N/A',
    totleHours: 8,
    floatingDay: false,
    holiday: true,
    vacation: false,
  },
]

export default Data
